# Generated by Django 4.2.4 on 2023-08-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_file',
            field=models.ImageField(blank=True, default='media/avatar.jpg', upload_to='media/'),
        ),
    ]
