# Generated by Django 4.2.4 on 2023-08-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_userprofile_avatar_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
